### ISSUE TITLE
now also the jack doesnt work

### ISSUE THREAD

**Issue by joaqocifmor1** [leifliddy/macbook12-audio-driver#11]
i do all the instructions in pop os (is Ubuntu in a way)  and the speaker dont work and the jack now also not work, kernel 5.13

**Comment by leifliddy** [comment]
What macbook do you have?

**Comment by joaqocifmor1** [comment]
macbook 8,1 i supposed it will work no?

**Comment by leifliddy** [comment]
Sorry, only the 2016 and 2017 models are supported. Something is different with the macbook8,1 (2015) model and I could never figure it out.

**Comment by leifliddy** [comment]
The headphone jack will work on the next kernel update. 
Or you you just remove the driver that this project installs with 
```
rm /lib/modules/$(uname -r)/updates/snd-hda-codec-cirrus.ko
depmod -A
reboot
```

**Comment by joaqocifmor1** [comment]
Thanks
