### ISSUE TITLE
Archlinux kernel 5.15 no sound from speaker

### ISSUE THREAD

**Issue by Mehaafa** [leifliddy/macbook12-audio-driver#14]
Hi. 

I tryed this driver with Mabook 9,1 and archlinux kernel 5.15.21.
My alsa-info.sh output is like this 
http://alsa-project.org/db/?f=b9bef8c3675f890b984a9a395a28d68791b42633

Driver is installed successfully without any trouble.
pavuontrol shows mixer status fine. 
But there is no sound coming out of speaker, just like it is muted but it is not :(

Any thoughts ? 
Please let me know if you need any other debuging info. 

And I apologize if my English is not sound right since English is not my first language. :)

Thank you very much.

**Comment by Mehaafa** [comment]
I found when I use grub boot loader, sound working but when I use rEfind then there is no sound.
I guess there is some difference in boot process between those two and that affects to driver, but I am not really clear about specific reason yet.
Thanks

**Comment by leifliddy** [comment]
That's pretty interesting. To be honest, I don't have much time to dedicate to this project going forward -- so I'm glad you found out what was causing the issue.
