### ISSUE TITLE
External mic not detected 

### ISSUE THREAD

**Issue by Amr3zzat** [leifliddy/macbook12-audio-driver#17]
I followed your instructions and everything worked fine, but alsa couldn't read my external mic as input but the output working fine , any thoghts?

**Comment by leifliddy** [comment]
So that's the main limitation with this driver is that the internal mic and headphone jack don't function with it.
Wait...you said external mic!? That should work...well a usb one anyway. What sort of external mic do you have?

**Comment by Amr3zzat** [comment]
I tried different headsets, logitech h111, even the Bluetooth headphone mic not detected too, only the internal one works

**Comment by Amr3zzat** [comment]
![image](https://user-images.githubusercontent.com/31932378/168393382-d467ec7e-447f-4448-83b9-1f9b8cb7d3a5.png)

My alsa info:
http://alsa-project.org/db/?f=3d9de36b5803d6595acfd99022aae9deb2eed3ab

**Comment by leifliddy** [comment]
The alsa info shows that your macbook model is a ```MacBookPro11,1```
This project only supports the macbook9,1 and 10,1 12-inch models. 
According to this page the speakers and headphones should work with the standard kernel driver on the MBP11.x, no mention of the microphone though. 
https://wiki.archlinux.org/title/MacBookPro11,x
