### ISSUE TITLE
Audio Jack becomes innactive ?

### ISSUE THREAD

**Issue by rmelendezz** [leifliddy/macbook12-audio-driver#30]
Hi, first of all thank you so much for all of the worked you did on getting the speakers working on this tiny but powerful laptop. I have got a Macbook 10,1 (2017) and the speakers are working flawlessly, however the Audio Jack seems to become inactive? 

Is there a way to use both the speakers and audio jack? or is it like I either have the Audio Jack working but not the speakers and vice versa?

Thanks again.

**Comment by leifliddy** [comment]
I was never able to figure that out. The audio jack works if you uninstall the `snd-hda-codec-cirrus` that this project creates (and using the stock kernel module)  -- but then the speakers won't work. So you can either have the speakers working or the audio jack working -- but not both at the same time. I simply don't have any more time to dedicate to this project. So someone else would have to sort that out...
